### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by EleotleCram** [jahnestacado/hermes-bus#1]
Is it missing a dependency on cli-color?

I got this (when using webpack):

ERROR in ./~/hermes-bus/lib/hermes-bus-reporter.js
Module not found: Error: Cannot resolve module 'cli-color' in ./node_modules/hermes-bus/lib
 @ ./~/hermes-bus/lib/hermes-bus-reporter.js 1:12-32

**Comment by jahnestacado** [comment]
Hi Marcel!

Please use the latest version.  At some point i included a state reporter
but wasn't a top priority so i removed it and the dependency was removed
later.

The latest version also has the before/after hooks.

Enjoy your holidays!

**Comment by EleotleCram** [comment]
AFAIK this is with latest version:

"hermes-bus": "^2.1.0",

(i.e. the version that installed when I did npm i --save hermes-bus, this evening)

**Comment by jahnestacado** [comment]
The error that you get is from an non existing file so probably the upgrade
to the latest version wasn't successfull. You can compare the hermes-bus
files in    your projects node_modules dir with the github files of the
master branch. Under the lib file you should only have the hermes-bus.js
file. You can also check if the module was installed globally in the past.
There is a chance that the module is not loaded from your projects local
node_modules dir.

**Comment by jahnestacado** [comment]
The problem was caused by a cached file in npm that wasn't removed from the npm repo.
